"""add unique constraint to user role name

Revision ID: 3e653d7df12b
Revises: 0b8e4787d0cf
Create Date: 2026-02-08 13:21:35.880090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e653d7df12b'
down_revision: Union[str, Sequence[str], None] = '0b8e4787d0cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Add unique constraint to user_roles.role_name."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_roles_role_name', ['role_name'])
    # ### end Alembic commands ###



def downgrade() -> None:
    """Remove unique constraint from user_roles.role_name."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_roles', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_roles_role_name', type_='unique')
    # ### end Alembic commands ###

